modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
